version: "3"
services: 
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    networks: 
      - dhnet
    command: "--smallfiles"
  web:
    build: .
    ports:
      - 8080:8080
      - 5858:5858
    depends_on: 
      - db
    links:
      - db
    networks:
      - dhnet
    volumes:
      - .:/usr/src/app
    environment: 
      MONGO_URL: "mongodb://db:27017"
    command: node --inspect=5858 server.js     

networks:
  dhnet:
